description: "Thank you for reporting a bug!"
name: bug
title: "[DATE]: [PROBLEM]"
labels: issue, needs-testing
body:
- type: textarea
  attributes:
    label: reproduction steps
    value: |
      1.
      2.
      3.
      ...
- type: textarea
  attributes:
    label: "What to do about it?"
