name: issue
title: "[DATE]: [PROBLEM]"
labels: issue, needs-testing
body:
- type: markdown
  attributes:
    value: "Bugs are the worst!"
- type: textarea
  attributes:
    label: "What's wrong?"

### problem: 
describe your problem here.

### resolution: 
describe the solution here
